# Translation Service Configuration
# =================================

# Default translation service to use
default_service: "google"  # Options: mock, google, deepl, huggingface

# Service-specific configurations
services:
  google:
    # Path to service account JSON file
    # Download from Google Cloud Console > IAM & Admin > Service Accounts
    credentials_path: "${GOOGLE_APPLICATION_CREDENTIALS}"
    
    # Google Cloud project ID
    project_id: "${GOOGLE_CLOUD_PROJECT}"
    
    # Rate limiting (requests per second)
    rate_limit: 10
    
    # Batch size for bulk translations
    batch_size: 100
    
  deepl:
    # DeepL API key
    api_key: "${DEEPL_API_KEY}"
    
    # API endpoint (free or pro)
    api_endpoint: "https://api-free.deepl.com/v2"
    
    # Rate limiting
    rate_limit: 5
    
  huggingface:
    # Model name for translation
    model_name: "Helsinki-NLP/opus-mt-en-es"
    
    # Device to use (cpu or cuda)
    device: "cpu"
    
    # Cache directory for models
    cache_dir: "~/.cache/huggingface"

# Caching configuration
cache:
  # Enable caching
  enabled: true
  
  # Cache backend (memory, redis, sqlite)
  backend: "sqlite"
  
  # Cache TTL in seconds (24 hours)
  ttl: 86400
  
  # SQLite cache database path
  sqlite_path: "cache/translation_cache.db"
  
  # Redis configuration (if using Redis)
  redis:
    host: "localhost"
    port: 6379
    db: 0
    password: null

# Language configuration
languages:
  # Supported language codes
  supported:
    - en  # English
    - es  # Spanish
    - fr  # French
    - de  # German
    - it  # Italian
    - pt  # Portuguese
    - ru  # Russian
    - ja  # Japanese
    - ko  # Korean
    - zh  # Chinese (Simplified)
    - ar  # Arabic
    - hi  # Hindi
    - tr  # Turkish
    - pl  # Polish
    - nl  # Dutch
    - sv  # Swedish
    - da  # Danish
    - no  # Norwegian
    - fi  # Finnish
    - cs  # Czech
  
  # Default source language (auto-detect if null)
  default_source: null
  
  # Default target language
  default_target: "en"

# Performance settings
performance:
  # Maximum concurrent requests
  max_concurrent_requests: 10
  
  # Request timeout in seconds
  timeout: 30
  
  # Retry configuration
  retry:
    max_attempts: 3
    backoff_factor: 2
    max_backoff: 60

# Logging configuration
logging:
  # Log level (DEBUG, INFO, WARNING, ERROR)
  level: "INFO"
  
  # Log translation requests
  log_requests: true
  
  # Log cache hits/misses
  log_cache: true
  
  # Log file path
  log_file: "logs/translation.log"