name: Kimera CI

on:
  push:
    branches: [ main, 'phase/*' ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install poetry
      - run: poetry install
      - name: Run unit tests
        run: poetry run pytest tests/unit/ -v
      - name: Run integration tests
        run: poetry run pytest tests/integration/ -v
      - name: Run functional tests
        run: poetry run pytest tests/functional/ -v
      - name: Run all tests with coverage
        run: poetry run pytest tests/ --cov=src/kimera --cov-report=term-missing
      - name: Verify SCAR implementation
        run: python scripts/verify_scar_implementation.py